language: node_js
node_js:
 - "node"

cache: npm

script: cd application && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: application/dist
  on:
    branch: master