language: node_js
node_js:
  - "node"

cache: npm

install:
  - cd application
  - npm ci

script:
  - npm run lint || travis_terminate 1
  - printf "VUE_APP_API_KEY=$VUE_APP_API_KEY\nVUE_APP_PROJECT_ID=$VUE_APP_PROJECT_ID\nVUE_APP_PUBLIC_VAPID_KEY=$VUE_APP_PUBLIC_VAPID_KEY\nVUE_APP_MESSAGING_SENDER_ID=$VUE_APP_MESSAGING_SENDER_ID\nVUE_APP_APP_ID=$VUE_APP_APP_ID\nVUE_APP_MEASUREMENT_ID=$VUE_APP_MEASUREMENT_ID\nVUE_APP_CUSTOM_SUBDIRECTORY=$VUE_APP_CUSTOM_SUBDIRECTORY" >> .env
  - printf cd public && "const process={env:{VUE_APP_API_KEY:$VUE_APP_API_KEY, VUE_APP_PROJECT_ID:$VUE_APP_PROJECT_ID, VUE_APP_PUBLIC_VAPID_KEY:$VUE_APP_PUBLIC_VAPID_KEY, VUE_APP_MESSAGING_SENDER_ID:$VUE_APP_MESSAGING_SENDER_ID, VUE_APP_APP_ID:$VUE_APP_APP_ID, VUE_APP_MEASUREMENT_ID:$VUE_APP_MEASUREMENT_ID}}" >> swenv.js && cd ..
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: application/dist
  on:
    branch: master
