language: node_js
node_js:
  - "node"

cache: npm

install: 
  - cd application
  - npm ci

script: 
 - npm run lint || travis_terminate 1
 - npm run build
 - printf "VUE_APP_API_KEY=$VUE_APP_API_KEY\nVUE_APP_PROJECT_ID=$VUE_APP_PROJECT_ID\n" >> .env

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: application/dist
  on:
    branch: master