name: Create release pull request
on:
  push:
    branches:
      - develop
jobs:
  createReleasePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Get current date
        id: current-datetime-generator
        run: echo "::set-output name=CURRENT_DATETIME::$(date '+%Y%m%d%H%M')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "RELEASE ${{steps.current-datetime-generator.outputs.CURRENT_DATETIME}}"
          body: |
            ## ぷるりの誓い
            - [ ] 私は、[ステージング環境][1]で今回の実装が仕様通りに動作する事を確認しました
            - [ ] 私は、ステージング環境で今回の実装によって既存機能がデグレっていない事を確認しました

            [1]: https://staging.crowdlinks.jp
