name: Prepare pull requests for review
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add labels to pull request
        id: label-pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["my label"]
            })
      - name: get pull request body
        id: get-pr-body
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
      - name: output pull request body
        run: echo "${{steps.get-pr-body.outputs.result}}"
