name: Prepare pull requests for review
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  prepare_pull_requests_for_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add labels to pull request
        id: label-pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["my label"]
            })
      - name: create or update pull request from develop
        if: github.event.pull_request.merged == true
        id: create-update-pr-from-develop
        uses: actions/github-script@v6
        with:
          script: |
            const founds = (await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              head: context.payload.pull_request.base.label
            })).data
            console.log("founds: ", founds);
            const exists = founds.length > 0
            if (!exists) {
              github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: "develop",
                base: "master",
                title: "develop to master",
                body: "Pull requests" +
                  `\n - ${context.payload.pull_request.html_url}` +
                  "\n"
              })
            } else {
              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: founds[0].number,
                body: founds[0].body +
                  `\n - ${context.payload.pull_request.html_url}` +
                  "\n"
              })
            }
