name: Prepare pull requests for review
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - ready_for_review
jobs:
  add_labels_to_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add labels to pull request
        id: label-pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["my label"]
            })
      - name: add assignees to pull request
        id: assign-pr
        uses: actions/github-script@v6
        with:
          script: |
            console.log("%o", context.payload.pull_request.user)
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assigness: []
            })
  create_or_update_pull_request_from_develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: create or update pull request from develop
        id: create-update-pr-from-develop
        uses: actions/github-script@v6
        with:
          script: |
            const ownership = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }
            const founds = (await github.rest.pulls.list({
              ...ownership,
              state: "open",
              head: context.payload.pull_request.base.label
            })).data
            const exists = founds.length > 0
            const contentsToAppend = `\n - ${context.payload.pull_request.html_url}`
            if (!exists) {
              const created = (await github.rest.pulls.create({
                ...ownership,
                head: "develop",
                base: "master",
                title: "develop to master",
                body: "Pull requests" + contentsToAppend
              })).data
              github.rest.issues.addLabels({
                ...ownership,
                issue_number: created.number,
                labels: ["my label"]
              })
            } else {
              github.rest.pulls.update({
                ...ownership,
                pull_number: founds[0].number,
                body: founds[0].body + contentsToAppend
              })
            }
