name: Prepare pull requests for review
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  prepare_pull_requests_for_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add labels to pull request
        id: label-pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["my label"]
            })
      - name: create or update pull request from develop
        if: github.event.pull_request.merged == true
        id: create-update-pr-from-develop
        uses: actions/github-script@v6
        with:
          script: |
            const ownership = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }
            const founds = (await github.rest.pulls.list({
              ...ownership,
              state: "open",
              head: context.payload.pull_request.base.label
            })).data
            const exists = founds.length > 0
            const contentsToAppend = `\n - ${context.payload.pull_request.html_url}`
            if (!exists) {
              const created = await github.rest.pulls.create({
                ...ownership,
                head: "develop",
                base: "master",
                title: "develop to master",
                body: "Pull requests" + contentsToAppend
              })
              github.rest.issues.addLabels({
                ...ownership,
                issue_number: created.number,
                labels: ["my label"]
              })
            } else {
              github.rest.pulls.update({
                ...ownership,
                pull_number: founds[0].number,
                body: founds[0].body + contentsToAppend
              })
            }
