name: Prepare pull requests for review
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  prepare_pull_requests_for_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: add labels to pull request
        id: label-pr
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["my label"]
            })
      - name: update pull request body
        id: update-pr-body
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            const prBody = pr.data.body + pr.data.html_url
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
              body: prBody
            })
